### ISSUE TITLE
Cannot find ./abi folder and json

### ISSUE THREAD

**Issue by alvarheras** [Nachoxt17/Arbitrage-Bot-between-UniSwap-and-SushiSwap-with-FlashLoans#1]
Hi, congratulations on this development

I'm trying to get it up and running so I can build on it.

I run into the problem that after successfully deploying my contract on the network. I throw the run command and it returns me that it cannot find the files inside the abi / folder. I don't know if I should fill this in manually. This is the mistake I take

![ffvfvfvfvfvf](https://user-images.githubusercontent.com/11508953/121886826-33628000-cd16-11eb-91d4-f4a117900175.PNG)

Still download json files to complete it but I'm afraid they are from other versions. These jsons inside abi / the ones I got from another repo, I'm afraid the versions and compilation don't match.

![vffvvffvvvfvf](https://user-images.githubusercontent.com/11508953/121886958-69076900-cd16-11eb-9854-abf60a2895be.PNG)

When I throw the first command

`npx hardhat run scripts/deploy.js --network ropsten`

![vffvvfvfvfv](https://user-images.githubusercontent.com/11508953/121887085-93f1bd00-cd16-11eb-8d2a-8ae45c0a5d58.PNG)

If I add the abi / xx.json manually the error that I find is this

![vfvfvfvfvfvfvfvfvfvf](https://user-images.githubusercontent.com/11508953/121887192-b84d9980-cd16-11eb-8f4e-7b4324f3cc0b.PNG)

In the end, I think that the necessary .abi / will not be generated. Thanks for your time

**Comment by alvarheras** [comment]
I substituted the json imports against the interface folder.

But now I run into this error.

```
DAI Amount:_ 500
Bot started!
(node:10568) UnhandledPromiseRejectionWarning: Error: call revert exception (method="getPair(address,address)", errorSignature=null, errorArgs=[null], reason=null, code=CALL_EXCEPTION, version=abi/5.1.2)
    at Logger.makeError (C:\Proyecto\CryptoBestPlatform\Arbitrage-Bot-between-UniSwap-and-SushiSwap-with-FlashLoans\node_modules\@ethersproject\logger\lib\index.js:180:21)
    at Logger.throwError (C:\Proyecto\CryptoBestPlatform\Arbitrage-Bot-between-UniSwap-and-SushiSwap-with-FlashLoans\node_modules\@ethersproject\logger\lib\index.js:189:20)
    at Interface.decodeFunctionResult (C:\Proyecto\CryptoBestPlatform\Arbitrage-Bot-between-UniSwap-and-SushiSwap-with-FlashLoans\node_modules\@ethersproject\abi\lib\interface.js:289:23)
    at Contract.<anonymous> (C:\Proyecto\CryptoBestPlatform\Arbitrage-Bot-between-UniSwap-and-SushiSwap-with-FlashLoans\node_modules\@ethersproject\contracts\lib\index.js:329:56)
    at step (C:\Proyecto\CryptoBestPlatform\Arbitrage-Bot-between-UniSwap-and-SushiSwap-with-FlashLoans\node_modules\@ethersproject\contracts\lib\index.js:48:23)
    at Object.next (C:\Proyecto\CryptoBestPlatform\Arbitrage-Bot-between-UniSwap-and-SushiSwap-with-FlashLoans\node_modules\@ethersproject\contracts\lib\index.js:29:53)
    at fulfilled (C:\Proyecto\CryptoBestPlatform\Arbitrage-Bot-between-UniSwap-and-SushiSwap-with-FlashLoans\node_modules\@ethersproject\contracts\lib\index.js:20:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10568) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10568) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I have also had some contracts pending for more than 50 minutes: S

**Comment by alvarheras** [comment]
I still get the same error as before, it seems that it does not synchronize with the node or contract created since when calling the getpairs () function

Later it comes with null

I am also not very convinced by the fact that the abi version is removed in the error -> version = abi / 5.1.2

**Comment by Nachoxt17** [comment]
> I still get the same error as before, it seems that it does not synchronize with the node or contract created since when calling the getpairs () function
> 
> Later it comes with null
> 
> I am also not very convinced by the fact that the abi version is removed in the error -> version = abi / 5.1.2

I also have the same problems, I can't make it work either, and I don't deserve the merit because I just mixed code of other people. Here it is another similar bot made by other person that is actually finished but I can't make it work, if you can, come back and tell me how did you did it please. https://github.com/6eer/uniswap-sushiswap-arbitrage-bot

**Comment by alvarheras** [comment]
Understood, I proceed to put myself with it and had several other options in view. Thanks for answering
